name: Python application test with Github Actions

on: [push]

env:
  SECRET_KEY: secret
  DATABASE_NAME: antoine_blog_db
  DATABASE_USER: db_admin
  DATABASE_PASSWORD: ''
  DATABASE_HOST: localhost
  DATABASE_PORT: 5432
  ADMIN_URL: admin/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        make install
    - name: Lint with flake8
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
    - name: Format code
      run: |
        make format
    
